#!/bin/bash

echo "Running Bootstrap ..."

# download conda
if ! command -v conda > /dev/null; then
  echo "Installing conda ..."
  curl -O https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh
  bash Miniconda3-py39_4.12.0-Linux-x86_64.sh
  source ~/.bashrc
fi

# download nvm + node
if ! command -v node > /dev/null; then
  echo "Installing nvm & node ..."
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  source ~/.bashrc
  nvm install 14
  nvm use 14
fi

# download neovim & vim-plug
if ! command -v nvim > /dev/null; then
  echo "Installing neovim & vim-plug ..."
  sudo apt install neovim
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi
